[package]
name = "spn_rust_bot"
version = "0.1.0"
authors = ["Thomas Kolb <cfr34k-git@tkolb.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.5"
uds     = "0.2.6"
